"use client";

import { useState } from "react";

import Navbar from '@/components/ui/Navbar';
import Footer from '@/components/sections/Footer';

const policies = [
  {
    id: "privacy",
    label: "Privacy Policy",
    date: "March 30, 2026",
    intro:
      "Lokalens values your privacy. This policy explains how we collect, use, store, and protect your personal information when you use our AI-powered demand forecasting platform.",
    articles: [
      {
        num: "01",
        title: "Information We Collect",
        body: "We may collect personal information such as your name, email address, phone number, company name, and any details you submit through forms or support requests. We also collect technical information including browser type, device details, pages visited, and usage analytics to continuously improve the Lokalens platform.",
      },
      {
        num: "02",
        title: "How We Use Information",
        body: "Collected information is used to provide and improve our forecasting services, respond to inquiries, send updates related to your requests, enhance platform performance, and maintain security. Data also powers our AI-driven demand predictions and localized retail analytics across Sri Lankan provinces.",
      },
      {
        num: "03",
        title: "Sharing of Information",
        body: "We do not sell your personal information. We may share data with trusted service providers under strict confidentiality obligations. Your business data and forecasting inputs are never shared with third parties without your explicit consent.",
      },
      {
        num: "04",
        title: "Data Retention",
        body: "We retain your data only as long as necessary to provide services or as required by applicable law. Business-specific forecasting data can be deleted upon request. Synthetic and contextual datasets used for regional demand modeling remain the property of Lokalens.",
      },
      {
        num: "05",
        title: "Your Rights",
        body: "You have the right to access, correct, or request deletion of your personal data at any time. To exercise these rights, contact us at privacy@lokalens.io. We will respond to all verified requests within 30 days.",
      },
    ],
  },
  {
    id: "terms",
    label: "Terms of Service",
    date: "March 30, 2026",
    intro:
      "These Terms of Service govern your access to and use of the Lokalens platform, including all forecasting outputs, recommendation engines, and future API integrations.",
    articles: [
      {
        num: "01",
        title: "Acceptance of Terms",
        body: "By accessing or using Lokalens, you agree to be bound by these Terms of Service. If you do not agree, please do not use our services. These terms apply to all users including SME owners, registered businesses, and API integrators.",
      },
      {
        num: "02",
        title: "Use of the Platform",
        body: "Lokalens grants you a limited, non-exclusive, non-transferable license to access and use the platform for lawful business purposes. You may not reverse-engineer, copy, or redistribute the forecasting engine, recommendation models, or any proprietary AI components of the platform.",
      },
      {
        num: "03",
        title: "Forecasting Accuracy Disclaimer",
        body: "Demand predictions generated by Lokalens are advisory in nature and based on contextual signals including regional, cultural, and behavioral data. They should not be relied upon as the sole basis for business decisions. Lokalens is not liable for financial losses arising from forecast inaccuracies.",
      },
      {
        num: "04",
        title: "User Data & Business Uploads",
        body: "When you upload sales history, POS data, or CSV records, you retain ownership of that data. You grant Lokalens a limited license to process this data solely to deliver personalized forecasting services. We will not use your proprietary business data to train shared models without your explicit consent.",
      },
      {
        num: "05",
        title: "Termination",
        body: "We reserve the right to suspend or terminate your access for violations of these terms or misuse of forecasting outputs. You may cancel your account at any time by contacting support@lokalens.io.",
      },
    ],
  },
  {
    id: "cookies",
    label: "Cookie Policy",
    date: "March 30, 2026",
    intro:
      "This Cookie Policy explains how Lokalens uses cookies and similar technologies to improve your experience across our forecasting dashboard and recommendation interfaces.",
    articles: [
      {
        num: "01",
        title: "What Are Cookies",
        body: "Cookies are small text files stored on your device when you visit Lokalens. They help us remember your preferences, maintain session state, and understand how users interact with our forecasting dashboard.",
      },
      {
        num: "02",
        title: "Types of Cookies We Use",
        body: "We use essential cookies for core platform functionality, analytics cookies to understand usage patterns, and preference cookies to remember your selected province and product filters. We do not use advertising or cross-site tracking cookies.",
      },
      {
        num: "03",
        title: "Managing Cookies",
        body: "You can control cookie settings through your browser preferences. Disabling essential cookies may affect platform functionality including forecasting inputs and dashboard state. Analytics cookies can be disabled without impacting core features.",
      },
    ],
  },
];

export default function LegalPage() {
  const [active, setActive] = useState("privacy");
  const section = policies.find((p) => p.id === active)!;

  return (
    <div
      style={{
        fontFamily: "'Plus Jakarta Sans', 'Manrope', sans-serif",
        background: "linear-gradient(160deg, #f0f6ff 0%, #ffffff 50%, #eaf3ff 100%)",
        minHeight: "100vh",
        color: "#0B1120",
      }}
    >
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap');

        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

        .policy-tab {
          font-family: 'Plus Jakarta Sans', sans-serif;
          font-size: 13px;
          font-weight: 600;
          border: none;
          background: transparent;
          cursor: pointer;
          padding: 9px 20px;
          border-radius: 100px;
          color: #6B7A99;
          transition: all 0.2s ease;
          white-space: nowrap;
        }
        .policy-tab:hover { color: #0B1120; background: #f0f4ff; }
        .policy-tab.active {
          background: #0A84FF;
          color: #fff;
          box-shadow: 0 4px 14px rgba(10, 132, 255, 0.35);
        }

        .article-row {
          display: grid;
          grid-template-columns: 48px 1fr;
          gap: 0 24px;
          padding: 32px 0;
          border-bottom: 1px solid rgba(10, 132, 255, 0.08);
          align-items: start;
        }
        .article-row:last-child { border-bottom: none; }

        .art-num {
          font-size: 11px;
          font-weight: 700;
          color: #0A84FF;
          letter-spacing: 0.06em;
          padding-top: 3px;
          font-family: 'Plus Jakarta Sans', sans-serif;
        }

        .art-title {
          font-size: 16px;
          font-weight: 700;
          color: #0B1120;
          margin-bottom: 10px;
          letter-spacing: -0.01em;
        }

        .art-body {
          font-size: 14.5px;
          font-weight: 400;
          line-height: 1.75;
          color: #4A5568;
        }

        .chip {
          display: inline-flex;
          align-items: center;
          gap: 6px;
          font-size: 12px;
          font-weight: 600;
          padding: 5px 12px;
          border-radius: 100px;
          background: rgba(10,132,255,0.08);
          color: #0A84FF;
          letter-spacing: 0.02em;
        }

        .chip-dot {
          width: 6px;
          height: 6px;
          border-radius: 50%;
          background: #0A84FF;
        }

@media (max-width: 600px) {
          .article-row { grid-template-columns: 1fr; gap: 6px 0; }
          .art-num { padding-top: 0; }
          .contact-card { padding: 28px 24px; }
        }
      `}</style>

      <Navbar />
      <div style={{ maxWidth: 820, margin: "0 auto", padding: "64px 24px 96px" }}>

        {/* Page Header */}
        <div style={{ marginBottom: 48 }}>
          <div className="chip" style={{ marginBottom: 20 }}>
            <span className="chip-dot" />
            Legal &amp; Policies
          </div>

          <h1
            style={{
              fontSize: "clamp(40px, 6vw, 64px)",
              fontWeight: 800,
              letterSpacing: "-0.03em",
              lineHeight: 1.1,
              color: "#0B1120",
              marginBottom: 16,
            }}
          >
            Legal{" "}
            <span style={{ color: "#0A84FF" }}>Documentation.</span>
          </h1>

          <p
            style={{
              fontSize: 16,
              fontWeight: 400,
              color: "#6B7A99",
              lineHeight: 1.65,
              maxWidth: 520,
            }}
          >
            Lokalens is committed to transparency in how we handle your data and govern
            platform usage across all Sri Lankan provinces.
          </p>
        </div>

        {/* Tab Switcher */}
        <div
          style={{
            display: "inline-flex",
            gap: 4,
            background: "#f0f4ff",
            padding: 4,
            borderRadius: 100,
            marginBottom: 40,
            flexWrap: "wrap",
          }}
        >
          {policies.map((p) => (
            <button
              key={p.id}
              className={`policy-tab${active === p.id ? " active" : ""}`}
              onClick={() => setActive(p.id)}
            >
              {p.label}
            </button>
          ))}
        </div>

        {/* Policy Card */}
        <div
          style={{
            background: "#ffffff",
            borderRadius: 20,
            border: "1px solid rgba(10,132,255,0.1)",
            boxShadow: "0 4px 24px rgba(10, 132, 255, 0.06)",
            padding: "40px 40px 32px",
          }}
        >
          {/* Card Header */}
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "flex-start",
              flexWrap: "wrap",
              gap: 12,
              marginBottom: 20,
              paddingBottom: 24,
              borderBottom: "1px solid rgba(10,132,255,0.08)",
            }}
          >
            <div>
              <h2
                style={{
                  fontSize: 22,
                  fontWeight: 800,
                  letterSpacing: "-0.02em",
                  color: "#0B1120",
                  marginBottom: 6,
                }}
              >
                {section.label}
              </h2>
              <p style={{ fontSize: 13, color: "#9BA8BF", fontWeight: 500 }}>
                Effective Date: {section.date}
              </p>
            </div>
            <span
              style={{
                fontSize: 11,
                fontWeight: 700,
                padding: "5px 12px",
                borderRadius: 100,
                background: "rgba(10,132,255,0.07)",
                color: "#0A84FF",
                letterSpacing: "0.06em",
                textTransform: "uppercase" as const,
                alignSelf: "flex-start",
              }}
            >
              Lokalens
            </span>
          </div>

          {/* Intro */}
          <p
            style={{
              fontSize: 15,
              fontWeight: 400,
              color: "#4A5568",
              lineHeight: 1.7,
              marginBottom: 8,
              paddingBottom: 24,
              borderBottom: "1px solid rgba(10,132,255,0.08)",
            }}
          >
            {section.intro}
          </p>

          {/* Articles */}
          <div>
            {section.articles.map((a) => (
              <div key={a.num} className="article-row">
                <div className="art-num">{a.num}</div>
                <div>
                  <div className="art-title">{a.title}</div>
                  <div className="art-body">{a.body}</div>
                </div>
              </div>
            ))}
          </div>
        </div>



      </div>
      <Footer />
    </div>
  );
}